### ISSUE TITLE
Add run subcommand

### ISSUE THREAD

**Issue by bradrn** [hasky-mode/hasky-stack#10]
In [the latest release of stack](https://github.com/commercialhaskell/stack/releases/tag/v1.9.1), a new subcommand was added:

> - A new sub command `run` has been introduced to build and run a specified executable
similar to `cabal run`. If no executable is provided as the first argument, it
defaults to the first available executable in the project.

This sort of command is perfect for hasky-stack - would it be possible to add it? Here's the code I'm using right now (it's really just copied from the code for the `exec` subcommand):

```elisp
(defun hasky-stack-run (cmd)
  "Execute \"stack run\" command running CMD."
  (interactive
   (list (read-string "Command to run: ")))
  (cl-destructuring-bind (app . args)
      (progn
        (string-match
         "^[[:blank:]]*\\(?1:[^[:blank:]]+\\)[[:blank:]]*\\(?2:.*\\)$"
         cmd)
        (cons (match-string 1 cmd)
              (match-string 2 cmd)))
    (hasky-stack--exec-command
     hasky-stack--project-name
     hasky-stack--last-directory
     (if (string= args "")
         (concat "run " app)
       (concat "run " app " -- " args)))))
(magit-define-popup-action 'hasky-stack-root-popup
  ?r "Run" 'hasky-stack-run)
```

**Comment by mrkkrp** [comment]
Well, go ahead and open a PR then!
