### ISSUE TITLE
Support for package.yaml

### ISSUE THREAD

**Issue by magthe** [hasky-mode/hasky-stack#12]
It would be really nice if `package.yaml` was as well supported by _hasky-stack_ as `<pkg>.cabal`.

**Comment by mrkkrp** [comment]
I do not use and do not recommend using `hspack`. I'd merge a PR implementing this though.

**Comment by magthe** [comment]
Well, `stack` has built-in support for it, and it uses a `package.yaml` itself: <https://github.com/commercialhaskell/stack/blob/master/package.yaml>

I'll see if I can cobble together a patch for it.

**Comment by mrkkrp** [comment]
How did it go?

**Comment by magthe** [comment]
I never got around to it and instead of leaving this open I thought it better to close it.
