### ISSUE TITLE
keybindings

### ISSUE THREAD

**Issue by kinsho6i7h** [hasky-mode/hasky-stack#13]
hi, cannot get the key bindings to work.

hasky-stack all works, just not the keybindings...

GNU Emacs 25.3.1

error: Key sequence <next> h e starts with non-prefix key <next>

**Comment by mrkkrp** [comment]
What did you put into your configuration and what are you typing exactly? In the readme I show a snippet which uses `<next>` and on my keyboard it's just "page down". It's OK for me because I have non-standard setup, but you may consider choosing something more conventional.

**Comment by kinsho6i7h** [comment]
For some odd reason, `<next> `isn't mapped in my system to page-down. Something is broken. However, I remapped to...

```
(require 'hasky-stack)
(global-set-key (kbd "<tab> h e") #'hasky-stack-execute)
(global-set-key (kbd "<tab> h h") #'hasky-stack-package-action)
(global-set-key (kbd "<tab> h i") #'hasky-stack-new)
```

All works well.
