### ISSUE TITLE
Detect file locations in doctest output better

### ISSUE THREAD

**Issue by neongreen** [hasky-mode/hasky-stack#9]
When I have a `doctest` testsuite, it prints failing tests in a slightly non-standard format. The result is that I can't jump to those locations from the compilation buffer.

![image](https://user-images.githubusercontent.com/1523306/37875343-ec583b8c-303d-11e8-9298-7b5d5c018b12.png)

**Comment by mrkkrp** [comment]
It's rather an issue with `doctest`. In compilation buffer we use `compilation-mode` and even if we somehow adjust what it recognizes as file positions, then it may stop working properly with ouput from other tools?

**Comment by neongreen** [comment]
Okay, I'll make a PR to doctest.

**Comment by neongreen** [comment]
https://github.com/sol/doctest/pull/200

**Comment by mrkkrp** [comment]
I consider this resolved then.
